// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBOI5TjDtbAsj5MWIeciuQYWQ24cjCAc0',
    appId: '1:523141448817:web:ca0e1c90bcc0601a7887d0',
    messagingSenderId: '523141448817',
    projectId: 'islamana-6139e',
    authDomain: 'islamana-6139e.firebaseapp.com',
    storageBucket: 'islamana-6139e.appspot.com',
    measurementId: 'G-QLJ1W0LCZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxwvv3jRfoQr9VPK909zanz0aFP3gZA-M',
    appId: '1:523141448817:android:42c07d48a16e44a97887d0',
    messagingSenderId: '523141448817',
    projectId: 'islamana-6139e',
    storageBucket: 'islamana-6139e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8lDW9FCHw9RXfsfsUnspZOv_kw11R6S8',
    appId: '1:523141448817:ios:279b2e788042906c7887d0',
    messagingSenderId: '523141448817',
    projectId: 'islamana-6139e',
    storageBucket: 'islamana-6139e.appspot.com',
    iosClientId: '523141448817-vme1o9q585v74huquj0npe9dh5ssuhjv.apps.googleusercontent.com',
    iosBundleId: 'com.islamina.islaminaApp',
  );
}
